# Generated by Django 4.1.2 on 2022-12-20 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_ec', models.CharField(max_length=255)),
                ('nom_ec', models.CharField(max_length=255, null=True)),
                ('credit', models.CharField(max_length=255, null=True)),
                ('note', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Excelfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel')),
            ],
        ),
        migrations.CreateModel(
            name='Ue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_ue', models.CharField(max_length=255)),
                ('nom_ue', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat_etud', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=255)),
                ('date_naiss', models.DateField(null=True)),
                ('decision', models.CharField(max_length=255, null=True)),
                ('ec', models.ManyToManyField(blank=True, related_name='etudiant', to='project.ec')),
            ],
        ),
        migrations.AddField(
            model_name='ec',
            name='ue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.ue'),
        ),
    ]
